# Generated by Django 5.2.3 on 2025-06-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_logentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='actions',
        ),
        migrations.AddField(
            model_name='logentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('deleted', 'Deleted'), ('archived', 'Archived')], default='created', max_length=10),
        ),
    ]
