# Generated by Django 5.2.3 on 2025-07-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_logentry_actions_logentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='user',
            field=models.BooleanField(default=True),
        ),
    ]
